# Generated by Django 5.1 on 2024-09-25 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        ('user_auth', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderitems',
            name='cart_items',
            field=models.ManyToManyField(to='order.cartitems'),
        ),
        migrations.AddField(
            model_name='orderitems',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='order_items',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.orderitems'),
        ),
        migrations.AddField(
            model_name='paymentdetails',
            name='order_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.orderdetails'),
        ),
        migrations.AddField(
            model_name='paymentdetails',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_auth.userpayment'),
        ),
    ]
